name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore CodeHub.sln

      - name: Build API
        run: dotnet build CodeHub.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test CodeHub.sln --configuration Release --no-build --collect:"XPlat Code Coverage"
